# Generated by Django 5.2.6 on 2025-09-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='clave_segura',
            new_name='contrasena',
        ),
    ]
